server:
  port: 8000
<<<<<<< HEAD

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # æŒ‡å®šeureka serveré€šä¿¡åœ°å€ï¼Œæ³¨æ„/eureka/å°å°¾å·´ä¸èƒ½å°‘

spring:
  application:
    name: microservice-provider-user
  jpa:       #ä½¿ç”¨JPAåˆ›å»ºæ•°æ®è¡¨
=======
spring:
  #  Ê¹ÓÃJPA½¨±í
  jpa:
>>>>>>> b18d64dc0ae1ef850f6b2234ad4acc37d8ff056d
    generate-ddl: false
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    dirver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/world?useUnicode=true&serverTimezone=GMT&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
<<<<<<< HEAD

=======
>>>>>>> b18d64dc0ae1ef850f6b2234ad4acc37d8ff056d
