server:
  port: 8001
<<<<<<< HEAD

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # æŒ‡å®šeureka serveré€šä¿¡åœ°å€ï¼Œæ³¨æ„/eureka/å°å°¾å·´ä¸èƒ½å°‘

spring:
  application:
    name: microservice-consumer-movie

=======
>>>>>>> b18d64dc0ae1ef850f6b2234ad4acc37d8ff056d
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
<<<<<<< HEAD
        #æš´éœ²metricsç«¯ç‚¹ï¼Œå¦‚éœ€æš´éœ²å¤šä¸ªï¼Œç”¨,åˆ†éš”ï¼›å¦‚éœ€æš´éœ²æ‰€æœ‰ç«¯ç‚¹ï¼Œç”¨'*'
        include: '*'
=======
        #±©Â¶metrics¶Ëµã£¬ÈçÐè±©Â¶¶à¸ö£¬ÓÃ,·Ö¸ô£»ÈçÐè±©Â¶ËùÓÐ¶Ëµã£¬ÓÃ'*'
        include: '*'
>>>>>>> b18d64dc0ae1ef850f6b2234ad4acc37d8ff056d
